default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: tdd_api_development

test:
  <<: *default
  database: tdd_api_test

production:
  <<: *default
  database: tdd_api_production
  username: tdd_api
  password: <%= ENV["NEUTRON_API_DATABASE_PASSWORD"] %>
